apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  values:
    ui:
      color: "#34577c"
      message: "Hello from dev environment"
    replicaCount: 2