apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  targetNamespace: podinfo
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  releaseName: podinfo
  install:
    createNamespace: true
    remediation:
      retries: 3
  values: {}  # Empty base values