---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/gimlet-io/capacitor
  ref:
    branch: main