name: Claude Code Review

on:
  # pull_request:
  #   types: [opened, synchronize]
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor.login }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "Event Payload: ${{ toJson(github.event) }}"
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
  claude-review:
    timeout-minutes: 10
    if: |
      (github.actor.login == 'david-shepard' &&
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.body, '@claude')) ||

      (github.actor.login == 'david-shepard' &&
        github.event_name == 'pull_request_review_comment' &&
        contains(github.event.comment.body, '@claude')) ||

      (github.actor.login == 'david-shepard' &&
        github.event_name == 'pull_request_review' &&
        contains(github.event.review.body, '@claude')) ||

      (github.actor.login == 'david-shepard' &&
        github.event_name == 'issues' &&
        (contains(github.event.issue.body, '@claude') ||
         contains(github.event.issue.title, '@claude')))
    # Optional: Filter by PR author
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      # id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.
            
            Use `gh pr review` with your Bash tool to leave create a pull request review
            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.
          
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr:*),Read,Grep,WebSearch"'

