name: Connect to Tailscale k8 cluster (debug)
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to apply to the node'
        required: false
        default: 'tag:gh-runner-node'
        type: string
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor.login }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "Event Payload: ${{ toJson(github.event) }}"
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
  tailscale:
    if: (github.event.sender.id == '12449626')
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: ${{ inputs.tags }}
      - name: Verify connection
        run: tailscale status
      - name: Show IP address
        run: tailscale ip -4
      - name: Show version
        run: tailscale version
      - name: Ping test
        run: ping -c 4 oracle-vm
